#debug: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true


management:
  endpoints:
    web:
      exposure:
        include: "*"