spring:
  security:
    user:
      name: user
      password: password
  thymeleaf:
    cache: false

# demo only:
logging:
  level:
    org:
      springframework:
        security: INFO
        boot:
          actuate:
            audit:
              listener:
                AuditListener: DEBUG
debug: true